name: Build and Push Docker Image to Aliyun

on: [push]

jobs:
  build_and_push:
    runs-on: ubuntu-latest



    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Aliyun Container Registry
      uses: docker/login-action@v1
      with:
        registry: registry.cn-shenzhen.aliyuncs.com
        username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
        password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@master
      with:
        context: .
        push: true
        tags: registry.cn-shenzhen.aliyuncs.com/xiaowangc/app-blogs:${{ github.sha }}
        
    - name: SSH Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # 执行更新操作的命令
          docker rm -f app-blogs
          docker run -itd -p 6001:80 -e TZ=Asia/Shanghai --name app-blogs --restart=always registry.cn-shenzhen.aliyuncs.com/xiaowangc/app-blogs:${{ github.sha }}

